/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SelectingImport } from './routes/selecting'
import { Route as CurrencyImport } from './routes/currency'
import { Route as CountryDetailsImport } from './routes/countryDetails'
import { Route as AirportImport } from './routes/airport'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SelectingRoute = SelectingImport.update({
  path: '/selecting',
  getParentRoute: () => rootRoute,
} as any)

const CurrencyRoute = CurrencyImport.update({
  path: '/currency',
  getParentRoute: () => rootRoute,
} as any)

const CountryDetailsRoute = CountryDetailsImport.update({
  path: '/countryDetails',
  getParentRoute: () => rootRoute,
} as any)

const AirportRoute = AirportImport.update({
  path: '/airport',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/airport': {
      preLoaderRoute: typeof AirportImport
      parentRoute: typeof rootRoute
    }
    '/countryDetails': {
      preLoaderRoute: typeof CountryDetailsImport
      parentRoute: typeof rootRoute
    }
    '/currency': {
      preLoaderRoute: typeof CurrencyImport
      parentRoute: typeof rootRoute
    }
    '/selecting': {
      preLoaderRoute: typeof SelectingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AirportRoute,
  CountryDetailsRoute,
  CurrencyRoute,
  SelectingRoute,
])

/* prettier-ignore-end */
